[package]
name = "rediz"
version = "1.3.37"
edition = "2021"
authors = [
    "Wahyu Syafiuddin <encrypt0r-x@protonmail.com>"
]

[dependencies]
serde-resp = "0.3.1"
tokio = { version = "1.29.0", features = ["full"] }